services:
  sonar-golc:
    image: fabiogos846/sonar-golc:latest # or :dev for the dev version (multi-arch: amd64 + arm64)
    container_name: sonar-golc
    ports:
      - "8091:8091"  # Web UI
      - "8090:8090"  # Results dashboard
    volumes:
      - ./data:/data  # persists config and results across runs
    restart: "unless-stopped"
